# Generated by Django 4.2.27 on 2026-02-26 11:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Matrícula')),
                ('ausencia_inicio', models.DateField(blank=True, null=True, verbose_name='Início do Período de Ausência')),
                ('ausencia_fim', models.DateField(blank=True, null=True, verbose_name='Fim do Período de Ausência')),
                ('precisa_trocar_senha', models.BooleanField(default=False, help_text='Se True, obriga o usuário a trocar a senha no próximo login.', verbose_name='Precisa trocar senha?')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=100, verbose_name='Nome do Cargo')),
                ('hierarquia', models.IntegerField(choices=[(1, 'Diretor'), (2, 'Gerente'), (3, 'Coordenador'), (4, 'Padrão')], default=4, verbose_name='Nível Hierárquico')),
                ('arquivado', models.BooleanField(default=False, verbose_name='Arquivar?')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#4f39f6', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#372aac', max_length=7, verbose_name='Cor Secundária')),
                ('emphasis_color', models.CharField(default='#c6d2ff', max_length=7, verbose_name='Cor de Destaque')),
                ('logo', models.ImageField(blank=True, default='theme/static/images/logo-icon.png', null=True, upload_to='logos/', verbose_name='Logo da Empresa')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(max_length=100, verbose_name='Nome do Documento')),
                ('requer_aprovacao_gestor', models.BooleanField(default=True, verbose_name='Requer aprovação do gestor?')),
                ('requer_aprovacao_diretor', models.BooleanField(default=True, verbose_name='Requer aprovação do diretor?')),
                ('dia_inicio', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Dia do mês que inicia o período (1-31). Ex: 1', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do mês de início do período de solicitação')),
                ('dia_fim', models.PositiveSmallIntegerField(blank=True, default=31, help_text='Dia do mês que encerra o período (1-31). Configure 31 para ir até o fim de qualquer mês.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do mês de fim do período de solicitação')),
                ('limite_dias_antecedencia', models.IntegerField(blank=True, default=0, help_text='Mínimo de dias entre hoje e a data do evento (ex: troca de plantão).', null=True, verbose_name='Dias de antecedência necessários')),
                ('definicao_formulario', models.JSONField(blank=True, default=list)),
                ('disponivel', models.BooleanField(default=True, help_text='Se ativo, este tipo de documento pode ser selecionado para novas solicitações.', verbose_name='Documento disponível para o colaborador?')),
                ('arquivado', models.BooleanField(default=False, verbose_name='Arquivar?')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE_ACEITE', 'Aguardando Aceite do Colega'), ('PENDENTE_GESTOR', 'Pendente (Gestor)'), ('PENDENTE_DIRETOR', 'Pendente (Diretor)'), ('PENDENTE_DP', 'Pendente (DP)'), ('LANCAMENTO', 'Aguardando Lançamento'), ('FINALIZADO', 'Finalizado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado')], default='PENDENTE_GESTOR', max_length=50, verbose_name='Status da Solicitação')),
                ('dados_preenchidos', models.JSONField(blank=True, default=dict, verbose_name='Dados Preenchidos')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('arquivado', models.BooleanField(default=False, verbose_name='Arquivar?')),
                ('aprovador_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes_pendentes', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador Atual')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador Solicitante')),
                ('colaborador_secundario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_secundarias', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador Secundário')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lotacao', models.CharField(max_length=100, verbose_name='Nome da Lotação')),
                ('arquivado', models.BooleanField(default=False, verbose_name='Arquivar?')),
                ('chefia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes_gerenciadas', to=settings.AUTH_USER_MODEL, verbose_name='Chefia da Lotação')),
                ('chefia_secundaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes_dirigidas', to=settings.AUTH_USER_MODEL, verbose_name='Chefia Secundária')),
                ('lotacao_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lotacao', verbose_name='Lotação Pai')),
            ],
            options={
                'verbose_name': 'Lotação',
                'verbose_name_plural': 'Lotações',
            },
        ),
        migrations.CreateModel(
            name='LogAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação da Solicitação'), ('CANCELAMENTO', 'Cancelado pelo Solicitante'), ('ACEITE_SECUNDARIO', 'Aceite pelo Colega'), ('RECUSA_SECUNDARIO', 'Recusado pelo Colega'), ('APROVADO_GESTOR', 'Aprovado pelo Gestor'), ('RECUSADO_GESTOR', 'Recusado pelo Gestor'), ('APROVADO_DIRETOR', 'Aprovado pelo Diretor'), ('RECUSADO_DIRETOR', 'Recusado pelo Diretor'), ('APROVADO_DP', 'Aprovado pelo DP'), ('RECUSADO_DP', 'Recusado pelo DP'), ('LANCADO', 'Lançado pelo DP'), ('COMENTARIO', 'Comentário Adicionado')], max_length=50)),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.TextField(blank=True)),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.solicitacao')),
            ],
            options={
                'verbose_name': 'Log de Aprovação',
                'verbose_name_plural': 'Logs de Aprovação',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lotacao', verbose_name='Lotação'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
