# Generated by Django 5.2.7 on 2025-10-27 12:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(max_length=100)),
                ('requer_aprovacao_gestor', models.BooleanField(default=False)),
                ('requer_aprovacao_diretor', models.BooleanField(default=False)),
                ('definicao_formulario', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cargo')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lotacao', models.CharField(max_length=100)),
                ('id_diretor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes_dirigidas', to=settings.AUTH_USER_MODEL)),
                ('id_gestor_imediato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes_gerenciadas', to=settings.AUTH_USER_MODEL)),
                ('id_lotacao_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lotacao')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lotacao'),
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE_ACEITE', 'Aguardando Aceite do Colega'), ('PENDENTE_GESTOR', 'Pendente (Gestor)'), ('PENDENTE_DIRETOR', 'Pendente (Diretor)'), ('PENDENTE_DP', 'Pendente (DP)'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado')], default='PENDENTE_GESTOR', max_length=50)),
                ('dados_preenchidos', models.JSONField(blank=True, default=dict)),
                ('id_aprovador_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes_pendentes', to=settings.AUTH_USER_MODEL)),
                ('id_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('id_colaborador_secundario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_secundarias', to=settings.AUTH_USER_MODEL)),
                ('id_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='LogAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação da Solicitação'), ('CANCELAMENTO', 'Cancelado pelo Solicitante'), ('ACEITE_SECUNDARIO', 'Aceite pelo Colega'), ('RECUSA_SECUNDARIO', 'Recusado pelo Colega'), ('APROVADO_GESTOR', 'Aprovado pelo Gestor'), ('RECUSADO_GESTOR', 'Recusado pelo Gestor'), ('APROVADO_DIRETOR', 'Aprovado pelo Diretor'), ('RECUSADO_DIRETOR', 'Recusado pelo Diretor'), ('PROCESSADO_DP', 'Processado pelo DP'), ('COMENTARIO', 'Comentário Adicionado')], max_length=50)),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.TextField(blank=True)),
                ('id_ator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.solicitacao')),
            ],
        ),
    ]
