# Generated by Django 5.2.7 on 2026-03-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='emphasis_color',
            field=models.CharField(default='#ebefff', max_length=7, verbose_name='Cor de Destaque'),
        ),
    ]
