# Generated by Django 5.2.7 on 2026-03-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_config_emphasis_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo da Empresa'),
        ),
    ]
