# Generated by Django 5.2.7 on 2025-10-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_cpf_alter_customuser_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id_cargo',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='id_lotacao',
            new_name='lotacao',
        ),
        migrations.RenameField(
            model_name='logaprovacao',
            old_name='id_ator',
            new_name='ator',
        ),
        migrations.RenameField(
            model_name='logaprovacao',
            old_name='id_solicitacao',
            new_name='solicitacao',
        ),
        migrations.RenameField(
            model_name='lotacao',
            old_name='id_gestor_imediato',
            new_name='chefia',
        ),
        migrations.RenameField(
            model_name='lotacao',
            old_name='id_diretor_responsavel',
            new_name='chefia_secundaria',
        ),
        migrations.RenameField(
            model_name='lotacao',
            old_name='id_lotacao_pai',
            new_name='lotacao_pai',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='id_aprovador_atual',
            new_name='aprovador_atual',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='id_colaborador',
            new_name='colaborador',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='id_colaborador_secundario',
            new_name='colaborador_secundario',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='id_tipo_documento',
            new_name='tipo_documento',
        ),
        migrations.AddField(
            model_name='cargo',
            name='hierarquia',
            field=models.IntegerField(choices=[(1, 'Diretor'), (2, 'Gerente'), (3, 'Coordenador'), (4, 'Padrão')], default=4),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ausencia_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ausencia_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
