# Generated by Django 5.2.7 on 2025-11-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_id_cargo_customuser_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='limite_dias_antecedencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
