# Generated by Django 5.2.7 on 2025-11-10 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipodocumento_data_fim_tipodocumento_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
