# Generated by Django 4.2.30 on 2026-09-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notificacao_excluida_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaprovacao',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação da Solicitação'), ('EDICAO', 'Edição da Solicitação'), ('CANCELAMENTO', 'Cancelado pelo Solicitante'), ('ACEITE_SECUNDARIO', 'Aceite pelo Colega'), ('RECUSA_SECUNDARIO', 'Recusado pelo Colega'), ('APROVADO_GESTOR', 'Aprovado pelo Gestor'), ('RECUSADO_GESTOR', 'Recusado pelo Gestor'), ('APROVADO_DIRETOR', 'Aprovado pelo Diretor'), ('RECUSADO_DIRETOR', 'Recusado pelo Diretor'), ('APROVADO_DP', 'Documento recebido pelo DP (aguardando a aprovação final)'), ('RECUSADO_DP', 'Recusado pelo DP'), ('LANCADO', 'Aprovado pelo DP'), ('COMENTARIO', 'Comentário Adicionado'), ('REVERSAO', 'Reversão de Decisão')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE_ACEITE', 'Aguardando Aceite do Colega'), ('PENDENTE_GESTOR', 'Pendente (Gestor)'), ('PENDENTE_DIRETOR', 'Pendente (Diretor)'), ('PENDENTE_DP', 'Pendente (DP)'), ('LANCAMENTO', 'Recebido pelo DP'), ('FINALIZADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado')], default='PENDENTE_GESTOR', max_length=50, verbose_name='Status da Solicitação'),
        ),
    ]
