# Generated by Django 5.2.7 on 2025-11-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_solicitacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaprovacao',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação da Solicitação'), ('CANCELAMENTO', 'Cancelado pelo Solicitante'), ('ACEITE_SECUNDARIO', 'Aceite pelo Colega'), ('RECUSA_SECUNDARIO', 'Recusado pelo Colega'), ('APROVADO_GESTOR', 'Aprovado pelo Gestor'), ('RECUSADO_GESTOR', 'Recusado pelo Gestor'), ('APROVADO_DIRETOR', 'Aprovado pelo Diretor'), ('RECUSADO_DIRETOR', 'Recusado pelo Diretor'), ('PROCESSADO_DP', 'Processado pelo DP'), ('RECUSADO_DP', 'Reusado pelo DP'), ('COMENTARIO', 'Comentário Adicionado')], max_length=50),
        ),
    ]
