# Generated by Django 5.2.7 on 2025-12-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_logaprovacao_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=False, help_text='Se True, obriga o usuário a trocar a senha no próximo login.'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE_ACEITE', 'Aguardando Aceite do Colega'), ('PENDENTE_GESTOR', 'Pendente (Gestor)'), ('PENDENTE_DIRETOR', 'Pendente (Diretor)'), ('PENDENTE_DP', 'Aguardando Lançamento (DP)'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado')], default='PENDENTE_GESTOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='definicao_formulario',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
