# Generated by Django 4.2.30 on 2026-09-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aviso_login_cancelamento_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='logaprovacao',
            name='decisao_anulada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversao', to='core.logaprovacao'),
        ),
    ]
