# Generated by Django 5.2.7 on 2025-12-16 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_precisa_trocar_senha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='dia_fim',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês que encerra o período (1-31). Configure 31 para ir até o fim de qualquer mês.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='dia_inicio',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês que inicia o período (1-31). Ex: 1', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='limite_dias_antecedencia',
            field=models.IntegerField(blank=True, help_text='Mínimo de dias entre hoje e a data do evento (ex: troca de plantão).', null=True),
        ),
    ]
