# Generated by Django 5.2.7 on 2025-12-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_tipodocumento_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='logaprovacao',
            options={'verbose_name': 'Log de Aprovação', 'verbose_name_plural': 'Logs de Aprovação'},
        ),
        migrations.AlterModelOptions(
            name='lotacao',
            options={'verbose_name': 'Lotação', 'verbose_name_plural': 'Lotações'},
        ),
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
    ]
