# Generated by Django 5.2.7 on 2025-12-30 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cargo_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='active',
            field=models.BooleanField(default=False, help_text='Se ativo, este tipo de documento pode ser selecionado para novas solicitações.'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='dia_fim',
            field=models.PositiveSmallIntegerField(blank=True, default=31, help_text='Dia do mês que encerra o período (1-31). Configure 31 para ir até o fim de qualquer mês.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='dia_inicio',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Dia do mês que inicia o período (1-31). Ex: 1', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
