# Generated by Django 5.2.7 on 2025-12-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tipodocumento_active_alter_tipodocumento_dia_fim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodocumento',
            old_name='active',
            new_name='disponivel',
        ),
    ]
