# Generated by Django 5.2.7 on 2025-12-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_active_tipodocumento_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
    ]
