# Generated by Django 5.2.7 on 2025-12-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cargo_arquivado_customuser_arquivado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='arquivado',
        ),
        migrations.AddField(
            model_name='lotacao',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
    ]
