# Generated by Django 5.2.7 on 2026-01-07 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_solicitacao_arquivado_lotacao_arquivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='dia_fim',
            field=models.PositiveSmallIntegerField(blank=True, default=31, help_text='Dia do mês que encerra o período (1-31). Configure 31 para ir até o fim de qualquer mês.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do mês de fim do período de solicitação'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='dia_inicio',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Dia do mês que inicia o período (1-31). Ex: 1', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do mês de início do período de solicitação'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Se ativo, este tipo de documento pode ser selecionado para novas solicitações.', verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='limite_dias_antecedencia',
            field=models.IntegerField(blank=True, default=0, help_text='Mínimo de dias entre hoje e a data do evento (ex: troca de plantão).', null=True, verbose_name='Dias de antecedência necessários'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='requer_aprovacao_diretor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='requer_aprovacao_gestor',
            field=models.BooleanField(default=True),
        ),
    ]
