# Generated by Django 5.2.7 on 2026-01-08 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_solicitacao_arquivado_alter_tipodocumento_dia_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='arquivado',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivar?'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='hierarquia',
            field=models.IntegerField(choices=[(1, 'Diretor'), (2, 'Gerente'), (3, 'Coordenador'), (4, 'Padrão')], default=4, verbose_name='Nível Hierárquico'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nome_cargo',
            field=models.CharField(max_length=100, verbose_name='Nome do Cargo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ausencia_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do Período de Ausência'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ausencia_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Período de Ausência'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lotacao', verbose_name='Lotação'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=False, help_text='Se True, obriga o usuário a trocar a senha no próximo login.', verbose_name='Precisa trocar senha?'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivar?'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='chefia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes_gerenciadas', to=settings.AUTH_USER_MODEL, verbose_name='Chefia da Lotação'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='chefia_secundaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes_dirigidas', to=settings.AUTH_USER_MODEL, verbose_name='Chefia Secundária'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='lotacao_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lotacao', verbose_name='Lotação Pai'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='nome_lotacao',
            field=models.CharField(max_length=100, verbose_name='Nome da Lotação'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='aprovador_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes_pendentes', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador Atual'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivar?'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador Solicitante'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='colaborador_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_secundarias', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador Secundário'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='dados_preenchidos',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados Preenchidos'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE_ACEITE', 'Aguardando Aceite do Colega'), ('PENDENTE_GESTOR', 'Pendente (Gestor)'), ('PENDENTE_DIRETOR', 'Pendente (Diretor)'), ('PENDENTE_DP', 'Aguardando Lançamento (DP)'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado')], default='PENDENTE_GESTOR', max_length=50, verbose_name='Status da Solicitação'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipodocumento', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivar?'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Se ativo, este tipo de documento pode ser selecionado para novas solicitações.', verbose_name='Documento disponível para o colaborador?'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nome_documento',
            field=models.CharField(max_length=100, verbose_name='Nome do Documento'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='requer_aprovacao_diretor',
            field=models.BooleanField(default=True, verbose_name='Requer aprovação do diretor?'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='requer_aprovacao_gestor',
            field=models.BooleanField(default=True, verbose_name='Requer aprovação do gestor?'),
        ),
    ]
